arch = [
  "acpi",
  "arch-install-scripts",
  "base",
  "base-devel",
  "bash-completion",
  "bat",
  "btrfs-progs",
  "cups",
  "cups-pdf",
  "dosfstools",
  "etckeeper",
  "ethtool",
  "exfatprogs",
  "fakeroot",
  "fwupd",
  "fzf",
  "gcc",
  "git",
  "git-delta",
  "github-cli",
  "htop",
  "inetutils",
  "iperf3",
  "jq",
  "keychain",
  "libcurl-compat",
  "linux",
  "linux-firmware",
  "linux-headers",
  "linux-lts",
  "linux-lts-headers",
  "lm_sensors",
  "lshw",
  "lsof",
  "lvm2",
  "make",
  "man-db",
  "man-pages",
  "moreutils",
  "mtr",
  "namcap",
  "nano",
  "ncdu",
  "net-tools",
  "nfs-utils",
  "nmap",
  "nss-mdns",
  "nvme-cli",
  "openssh",
  "os-prober",
  "pacman-contrib",
  "pacutils",
  "parted",
  "patch",
  "polkit-gnome",
  "powertop",
  "pwgen",
  "python",
  "python-virtualenv",
  "python-pip",
  "rclone",
  "refind",
  "reflector",
  "rsync",
  "screen",
  "sipcalc",
  "smartmontools",
  "starship",
  "strace",
  "sudo",
  "sysstat",
  "tailscale",
  "tcpdump",
  "tree",
  "unrar",
  "unzip",
  "vi",
  "vim",
  "wget",
  "which",
  "whois",
  "wireguard-tools",
  "xfsprogs",
  "acpi_call",
  "devtools",
  "e2fsprogs",
  "ntp",
  "rbw",
  "zip",
  "iftop",
  "openbsd-netcat",
  "traceroute",
  "netctl",
  "bind",
  "openssl-1.1",
  "chezmoi",
  "gptfdisk",
]
