arch = [
  "alacritty",
  "bitwarden",
  "chromium",
  "dialog",
  "dunst",
  "feh",
  "ffmpegthumbnailer",
  "file-roller",
  "firefox",
  "gedit",
  "gimp",
  "gnome-calculator",
  "gnome-font-viewer",
  "gnome-keyring",
  "gparted",
  "gthumb",
  "gtk-engines",
  "gufw",
  "gvfs-nfs",
  "gvfs-smb",
  "i3-wm",
  "jre-openjdk",
  "libappindicator-gtk3",
  "libpng",
  "light-locker",
  "lightdm",
  "lightdm-gtk-greeter",
  "lightdm-slick-greeter",
  "lxappearance",
  "lxqt-policykit",
  "lxterminal",
  "maim",
  "meld",
  "nemo",
  "nemo-fileroller",
  "nemo-preview",
  "network-manager-applet",
  "networkmanager",
  "networkmanager-openvpn",
  "nextcloud-client",
  "notification-daemon",
  "numlockx",
  "otf-fantasque-sans-mono",
  "otf-font-awesome",
  "7zip",
  "picom",
  "polybar",
  "redshift",
  "remmina",
  "rofi",
  "smplayer",
  "system-config-printer",
  "terminus-font",
  "ttf-droid",
  "ttf-font-awesome",
  "ttf-hack",
  "ttf-inconsolata",
  "ttf-roboto",
  "tumbler",
  "udiskie",
  "upower",
  "vlc",
  "x264",
  "xautolock",
  "xbindkeys",
  "xclip",
  "xdotool",
  "papirus-icon-theme",
  "ttf-fira-code",
  "yubikey-manager-qt",
  "yubikey-manager",
  "yubikey-personalization-gui",
  "transmission-gtk",
  "freerdp",
  "torbrowser-launcher",
  "tigervnc",
  "dhcpcd",
  "nodejs",
  "nemo-share",
  "deskflow",
]
