arch = [
  "staticcheck",
  "act",
  "ansible",
  "ansible-lint",
  "automake",
  "docker",
  "go",
  "packer",
  "podman",
  "terraform",
  "vagrant",
  "yamllint",
  "go-yq",
  "tmate",
  "vault",
  "gron",
  "glow",
  "difftastic",
  "hugo",
  "sshfs",
  "gopls",
  "git-absorb",
  "pre-commit",
  "woodpecker-cli",
]
