[env]
WINIT_X11_SCALE_FACTOR = "1"
TERM = "xterm-256color"

[font]
size = 9.0

[font.bold]
family = "Fira Code"
style = "Retina"

[font.bold_italic]
family = "Fira Code"
style = "Retina"

[font.italic]
family = "Fira Code"
style = "Retina"

[font.normal]
family = "Fira Code"
style = "Retina"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 100000
multiplier = 5

[terminal.shell]
args = ["--login"]
program = "/usr/bin/bash"

[window]
dynamic_title = true
title = "Alacritty"

[window.padding]
x = 15
y = 10

[general]
live_config_reload = true

import = [
  "~/.config/alacritty/themes/dark.toml",
]

[terminal]
